# Paramètre d'entrée : environnement cible (ex: dev, prd)
parameters: 
  env: dev

# Définition des stages de la pipeline
stages:

  # === STAGE 1 : PLAN ===
  - stage: plan_${{ parameters.env }}
    dependsOn: []  # Ce stage n’a pas de dépendance, il peut s’exécuter directement
    displayName: Générer le plan Terraform pour ${{ parameters.env }}
    
    # Variables groupées dans Azure DevOps (group infracloud)
    variables: 
      - group: infracloud

    jobs:
      - job: Plan
        steps:

        # Étape 1 : Initialisation de Terraform avec Azure CLI (authentification OIDC)
        - task: AzureCLI@2
          displayName: "Terraform Init in ${{ parameters.env }}"
          inputs:
            azureSubscription: "man-az-we-exemple-${{ parameters.env }}-sp-provision"
            scriptType: bash
            scriptLocation: inlineScript
            addSpnToEnvironment: true
            inlineScript: |
              # Configuration de l'authentification OIDC
              echo "🔐 Configuration de l'authentification avec OIDC"
              export ARM_CLIENT_ID=$servicePrincipalId
              export ARM_OIDC_TOKEN=$idToken
              export ARM_TENANT_ID=$tenantId
              export ARM_SUBSCRIPTION_ID=$(kv-subscription-${{ parameters.env }})
              export ARM_USE_OIDC=true

              # Injection dynamique de la Subscription ID dans le provider
              sed -i "s/__SUBSCRIPTIONID__/$(kv-subscription-${{ parameters.env }})/" providers.tf

              # Authentification Git pour récupérer les modules Terraform si besoin
              git config --global http.https://exemple@dev.azure.com.extraheader "AUTHORIZATION: bearer $(System.AccessToken)"

              # Initialisation de Terraform avec le backend distant
              terraform init -backend-config="backend/${{ parameters.env }}.conf"

              # Nettoyage de la config Git
              git config --global --unset-all http.https://exemple@dev.azure.com.extraheader

        # Étape 2 : Exécution du plan Terraform
        - task: TerraformTaskV4@4
          displayName: "Terraform Plan in ${{ parameters.env }}"
          inputs:
            provider: 'azurerm'
            command: 'plan'
            commandOptions: '-var-file="vars/${{ parameters.env }}.tfvars" -out=${{ parameters.env }}.tfplan -input=false'
            environmentServiceNameAzureRM: "man-az-we-exemple-${{ parameters.env }}-sp-provision"

  # === STAGE 2 : APPLY ===
  - stage: apply_${{ parameters.env }}
    displayName: Déploiement Terraform vers ${{ parameters.env }}
    
    variables:
      - group: infracloud

    jobs:
      - deployment: Apply
        environment:
          name: exemple-${{ parameters.env }}  # Environnement Azure DevOps (utile pour les approbations)
        displayName: "Terraform Apply"
        strategy:
          runOnce:
            deploy:
              steps:

                # Étape unique : application du plan Terraform
                - task: TerraformTaskV4@4
                  displayName: "Terraform Apply in ${{ parameters.env }}"
                  inputs:
                    provider: 'azurerm'
                    command: 'apply'
                    commandOptions: '${{ parameters.env }}.tfplan'
                    environmentServiceNameAzureRM: "man-az-we-exemple-${{ parameters.env }}-sp-provision"
